### PR TITLE
Fix views that confuse users on actual command execution

### LINKED ISSUE #137: [PE-D][Tester A] Filtered list is searched after showrelated command
When I showrelated a contact, the filtered list appears. However, if I want to filter another contact's relations, it searches the filtered list and tries to get relationships from that filtered list instead of searching through the original person list. This means that the results turn up as 0.

For example when I relate i/11 and i/12 here, and relate i/13 and i/14 together:

Then when I showrelated i/11 it displays i/12:

However, next when I try showrelated i/13, i/14 does not appear and instead it says 0 persons listed:

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: Alteqa/ped#3

### LINKED ISSUE #145: [PE-D][Tester E] Command is wrong but still shows result anyways
I tried to relate i/1 and i/1 which is supposed to not happen but still got the result despite it being not allowed to happen.

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: wolffe88/ped#9

### LINKED ISSUE #160: [PE-D][Tester C] Rendering for relate command not accurate
relate command adds the relation as expected

but the message display does not correspond, reflects "1 person listed", when it should be "relation added" or something along those lines

the results display panel also lists only id 4, instead of both id 4 and 5

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: kaitinghh/ped#13

### LINKED ISSUE #172: [PE-D][Tester B] Relation doesn't work as expected or as it should
Steps to reproduce:
1. List all the contacts `list`
2. Relate `ID 2` with any given id, I took `ID 4`

3. Now, do the same with another id, for instance relate `ID 2` with `ID 7`
4. Now use this command `showrelated i/7` 

**Expected:** `ID 7` should display a relation with `ID 2` as well since they are both related now

**Actual:** Shows the below when pasting this command `showrelated i/7`

-------------
Labels: `type.FeatureFlaw` `severity.High`
original: gauravuj/ped#5

### PR DESCRIPTION
**Pull request by starsia**
# Bug fixes related to view not refreshing:
- Refresh view so chained commands (not using `list` command to reset view) will not mislead user. See 1. and 2. 
- Remove "successful" single contact viewed despite an invalid reflexive `relate` command. See 3.

1. **Fixes #172** , screenshot of bug submitted by tester below:
image

2. **Fixes #160**, screenshot of bug submitted by tester below:
image

3. **Fixes #145**, screenshot of bug submitted by tester below:
image
image

### CODE REVIEW

File: src/main/java/seedu/address/logic/commands/RelateCommand.java [hunk 1]
```diff
@@ -40,9 +40,13 @@ public RelateCommand(IdContainsDigitsPredicate predicate) {
     @Override
     public CommandResult execute(Model model) throws CommandException {
         requireNonNull(model);
+        // reset user view from any previous commands
+        model.clearFilter();
+
         // if ids are valid AND exists, model will display them, otherwise, it will be an empty list
         model.stackFilters(predicate);
```
Comment (shaunlxw) [inline src/main/java/seedu/address/logic/commands/RelateCommand.java]: Can I suggest moving the
```
model.clearFilter();
model.stackFIlters(predicate);
```
to after line 65? I think it would be better as logically, we want the UI to only update after the completion of the action. Doing so also will prevent a `clearFilter()` -> `stackFilters(...)` -> `clearFilter()` happening when the ids are equal (although it is unnoticeable on the UI but it is happening).

File: src/main/java/seedu/address/logic/commands/UnrelateCommand.java [hunk 2]
```diff
@@ -42,9 +42,13 @@ public UnrelateCommand(IdContainsDigitsPredicate predicate) {
     @Override
     public CommandResult execute(Model model) throws CommandException {
         requireNonNull(model);
+        // reset user view from any previous commands
+        model.clearFilter();
+
         // if ids are valid AND exists, model will display them, otherwise, it will be an empty list
         model.stackFilters(predicate);
```
Comment (shaunlxw) [inline src/main/java/seedu/address/logic/commands/UnrelateCommand.java]: I think could do the same as above, to move this to after line 67.

**Review by shaunlxw — APPROVED** [review]
LGTM, apart from some minor unnoticeable changes required. 👍

**Comment by tanjieling0** [comment]
Fixes #137 as well
