### PR TITLE
Fix find by remark to allow more than one word

### LINKED ISSUE #140: [PE-D][Tester C] Find r/ command not working
The UG says this command should work but it does not work and the error message does not correspond to the input

Flow of order: I tried command in bug report #6 first, then I tried this command #7, seems to be stalling

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: kaitinghh/ped#7

### PR DESCRIPTION
**Pull request by shaunlxw**
Fixes #140.

Previous implementation only allows `r/` to take in one word per `r/`, i.e. does not work for `r/marketing IC`.

Behaviour in this commit:
* find r/has dog matches r/has a dog
* find r/has dog matches r/dog has
* find r/dog does **not** match r/dogs, or vice versa

### CODE REVIEW

File: src/main/java/seedu/address/model/person/filter/RemarkContainsKeywordsPredicate.java [hunk 1]
```diff
@@ -36,7 +37,8 @@ public String formatFilter() {
     @Override
     public boolean test(Person person) {
         return keywords.stream()
-                .anyMatch(keyword -> StringUtil.containsWordIgnoreCase(person.getRemark().value, keyword))
+                .anyMatch(keyword -> Arrays.stream(keyword.split("\\s+"))
```
Comment (purivirakarin) [inline src/main/java/seedu/address/model/person/filter/RemarkContainsKeywordsPredicate.java:40]: LGTM

**Review by purivirakarin — APPROVED** [review]
The code has been changed as mentioned in PR details, and testing looks good to me.
