### PR TITLE
Bug fix: error msg for delete and edit command

### LINKED ISSUE #74: Fix bug: output accurate error message for Edit/Delete command

### PR DESCRIPTION
**Pull request by shaunlxw**
Fixes #74.

* Output accurate error message for invalid id fields for delete and edit command
  * Previous: If name/id is in the wrong format (e.g. n/Sha@un), error message is "Invalid command format! ..."
  * Fix: If name/id is in the wrong format, error message is "(Name/Id).MESSAGE_CONSTRAINTS"
* Add test to check accurate error message
* Add test to check repeated id value

### CODE REVIEW

File: src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java [hunk 1]
```diff
@@ -25,8 +28,30 @@ public void parse_validArgs_returnsDeleteCommand() {
...
+
+        // non numerical id
+        assertParseFailure(parser, " i/one", Id.MESSAGE_CONSTRAINTS);
+
+        // empty id
+        assertParseFailure(parser, " i/", Id.MESSAGE_CONSTRAINTS);
+    }
+
+    @Test
+    public void parse_repeatedId_throwsParseException() {
```
Comment (tanjieling0) [inline src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java]: perhaps instead of repeatedId, we could duplicatePrefix for naming?

**Review by tanjieling0 — APPROVED** [review]
LGTM

File: src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java (hunk 1 above)
Comment (shaunlxw) [reply src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java]: Sounds more accurate! 👍
