### PR TITLE
Fix export command file path and mismatch data in CSV file

### LINKED ISSUE #156: [PE-D][Tester E] Information of exported csv differs from information on the program
Some information from the program does not match the information of the csv after exporting

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: wolffe88/ped#11

### LINKED ISSUE #159: [PE-D][Tester E] CSV fields and data mismatched
The prooduct field should not have C++, the preference field should not have python and TOS should not have eggs.

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: wolffe88/ped#12

### LINKED ISSUE #177: [PE-D][Tester C] Export csv not found
I am unable to find the said exported csv anywhere on my laptop. If the command indeed works as expected, it would help if you could specify where the csv was exported to in the UG. 

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: kaitinghh/ped#18

### PR DESCRIPTION
**Pull request by nuyer**
1 Fix #156 and #159 Mismatch info in exported csv file
Correct String format when writing the CSV file

2 Fix #177 Cannot find CSV file
Change file path for exported file to be in same directory as jar file

3 Standard empty field to an empty string "" instead of "-"

### CODE REVIEW

File: src/main/java/seedu/address/logic/parser/AddCommandParser.java [hunk 1]
```diff
@@ -115,8 +115,8 @@ private static Person createPerson(
             Optional<List<String>> optionalSkills = Optional.ofNullable(argMultimap.getAllValues(PREFIX_SKILLS));
             Department department = optionalDepartment
                     .map(Department::new)
-                    .orElseGet(() -> new Department("-"));
-            JobTitle jobTitle = optionalJobTitle.map(JobTitle::new).orElseGet(() -> new JobTitle("-"));
+                    .orElseGet(() -> new Department(" "));
```
Comment (purivirakarin) [inline src/main/java/seedu/address/logic/parser/AddCommandParser.java]: Why we put ` ` instead of ``.

File: src/main/java/seedu/address/logic/parser/AddCommandParser.java [hunk 2]
```diff
@@ -115,8 +115,8 @@ private static Person createPerson(
...
+            JobTitle jobTitle = optionalJobTitle.map(JobTitle::new).orElseGet(() -> new JobTitle(" "));
```
Comment (purivirakarin) [inline src/main/java/seedu/address/logic/parser/AddCommandParser.java]: Same as mentioned above

File: src/main/java/seedu/address/logic/parser/AddCommandParser.java [hunk 3]
```diff
@@ -131,7 +131,7 @@ private static Person createPerson(
                     .orElse(Collections.emptyList()));
             TermsOfService termsOfService = optionalTermsOfService
                     .map(TermsOfService::new)
-                    .orElseGet(() -> new TermsOfService("-"));
+                    .orElseGet(() -> new TermsOfService(" "));
```
Comment (purivirakarin) [inline src/main/java/seedu/address/logic/parser/AddCommandParser.java]: Same as mentioned above.

File: src/main/java/seedu/address/logic/parser/ExportCommandParser.java [hunk 4]
```diff
@@ -48,12 +48,9 @@ private boolean isValidFilename(String filename) {
...
         }
 
-        // Check for special characters
-        String restrictedChars = "<>:\"/\\|?*";
-        for (char c : restrictedChars.toCharArray()) {
-            if (filename.indexOf(c) != -1) {
-                return false;
-            }
+        //Only Alphanumerical, underscores, hyphens and periods are allowed
+        if (!filename.matches("[a-zA-Z0-9_\\-.]*")) {
```
Comment (purivirakarin) [inline src/main/java/seedu/address/logic/parser/ExportCommandParser.java:60]: Nice!

File: src/main/java/seedu/address/model/person/Client.java [hunk 5]
```diff
@@ -44,6 +44,19 @@ public Products getProducts() {
...
+     * Returns the products preferred by the client.
+     *
+     * @return The products preferred by the client as a String.
+     */
+    public String getProductsAsString() {
+        String result = String.join(", ", products.getProducts());
+        if (result.isEmpty()) {
+            return result;
+        }
+        return "\"" + result + "\"";
```
Comment (purivirakarin) [inline src/main/java/seedu/address/model/person/Client.java:57]: Why we encapsulate the list of products using `"` and `"`. I personally think that in the exported csv file should not have this as it seems less practical to a user to copy over and use the data.

File: src/main/java/seedu/address/model/person/Employee.java [hunk 6]
```diff
@@ -66,6 +66,19 @@ public Skills getSkills() {
...
+     * Returns the skills of the employee.
+     *
+     * @return The skills of the employee as a string.
+     */
+    public String getSkillsAsString() {
+        String result = String.join(", ", skills.getSkills());
+        if (result.isEmpty()) {
+            return result;
+        }
+        return "\"" + result + "\"";
```
Comment (purivirakarin) [inline src/main/java/seedu/address/model/person/Employee.java:79]: Same as above

File: src/main/java/seedu/address/model/person/Person.java [hunk 7]
```diff
@@ -117,11 +117,14 @@ public String getTagsAsString() {
...
-        // Remove the last comma and space if there are any tags
         if (stringBuilder.length() > 0) {
             stringBuilder.delete(stringBuilder.length() - 2, stringBuilder.length());
         }
-        return stringBuilder.toString();
+        String result = stringBuilder.toString();
+        if (result.isEmpty()) {
+            return "";
+        }
+        return "\"" + result + "\"";
```
Comment (purivirakarin) [inline src/main/java/seedu/address/model/person/Person.java:127]: Same as above

File: src/main/java/seedu/address/model/person/Supplier.java [hunk 8]
```diff
@@ -45,6 +45,19 @@ public Products getProducts() {
...
+     * Returns the products preferred by the client.
+     *
+     * @return The products preferred by the client as a String.
+     */
+    public String getProductsAsString() {
+        String result = String.join(", ", products.getProducts());
+        if (result.isEmpty()) {
+            return result;
+        }
+        return "\"" + result + "\"";
```
Comment (purivirakarin) [inline src/main/java/seedu/address/model/person/Supplier.java:58]: same as above

File: src/test/java/seedu/address/logic/utils/CsvExporterTest.java [hunk 9]
```diff
@@ -66,20 +65,18 @@ public void createDataList_correctlyConstructedList() {
...
 
         assertArrayEquals(new String[]{"1", "John Doe", "1234567890", "john@example.com", "\"123 Main St\"",
-            "some remarks", "", "HR", "Manager", "Java, SQL", "", "", ""}, dataList.get(1));
+            "some remarks", "", "HR", "Manager", "\"Java, SQL\"", "", "", ""}, dataList.get(1));
         assertArrayEquals(new String[]{"2", "Jane Smith", "9876543210", "jane@example.com", "\"456 Elm St\"",
-            "some remarks", "", "", "", "", "Product A", "Likes discounts", ""}, dataList.get(2));
+            "some remarks", "", "", "", "", "\"Product A\"", "Likes discounts", ""}, dataList.get(2));
         assertArrayEquals(new String[]{"3", "Acme Inc", "5555555555", "info@acme.com", "\"789 Oak St\"",
-            "some remarks", "", "", "", "", "Product X", "", "30 days"}, dataList.get(3));
+            "some remarks", "", "", "", "", "\"Product X\"", "", "30 days"}, dataList.get(3));
```
Comment (purivirakarin) [inline src/test/java/seedu/address/logic/utils/CsvExporterTest.java]: Same as above

**Review by purivirakarin — CHANGES_REQUESTED** [review]
The changes mostly look good to me. There are some comments i left that can be taken a look.

File: src/main/java/seedu/address/model/person/Client.java (hunk 5 above)
Comment (nuyer) [reply src/main/java/seedu/address/model/person/Client.java:57]: How CSV file store data is that it will read the string and it will cut the content tp then new cell when comma (,)is found. Therefore, to storetext that contains "," (for tags, skills, prods fields) we need to add " in front and an the end for the csv to know that these commas are a part of content not to split the content

**Review by purivirakarin — APPROVED** [review]
